### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by ArnavK-09** [joshnuss/svelte-supabase#9] opened 2021-08-28 12:34 UTC
![image](https://user-images.githubusercontent.com/69188140/131218031-7abb29e7-4e8c-4cd2-8ad7-a6be690d60d0.png)

**Comment by joshnuss** [comment] 2021-08-29 03:25
Hi @ArnavK-09 ,

I think this issue is a duplicate of #7, can you try the suggestions there and LMK if that fixes it.

**Closed as completed** 2021-08-31 14:16 UTC
Labels: duplicate
