### ISSUE TITLE
Unable to set up Sveltekit supabase 

### ISSUE THREAD

**Issue by pdk1000** [joshnuss/svelte-supabase#10] opened 2021-09-03 10:11 UTC
From a fresh installation using git bash on windows 10 I get this error:

Access to joshnuss/svelte-supabase denied. If you think it's an error, make sure you have an SSH key set up and linked to your Git account. If the repository is public and you don't want to configure SSH, use the --no-ssh flag.

**Comment by joshnuss** [comment] 2021-09-05 09:13
Hi @pdk1000,

This is a duplicate of #7 and #9. Please try recommendations mentioned in the comments, and if it's still not working, leave comments in #7.

**Closed as completed by joshnuss** 2021-09-05 09:13 UTC
Labels: duplicate

**Comment by pdk1000** [comment] 2021-09-06 11:06
Thank you.
https://github.com/joshnuss/svelte-supabase/issues/7#:~:text=Tested%20on%20a,work%20just%20fine.
This fixed worked for me
