### ISSUE TITLE
How To Fix???

### ISSUE THREAD

**Issue by ArnavK-09** [joshnuss/svelte-supabase#11] opened 2021-09-05 07:18 UTC
![image](https://user-images.githubusercontent.com/69188140/132118831-70dc602c-9a93-40ce-aa49-a3b3cbbce26f.png)

**Comment by joshnuss** [comment] 2021-09-05 09:11
Hi @ArnavK-09 

This is a duplicate of #7, #9, #10. Please follow recommendation in #7, and comment there if there is still an issue.

**Closed as completed by joshnuss** 2021-09-05 09:11 UTC
Labels: duplicate
